/**
 * render-deck.ts — render a PRISM Ads Connector deck spec (the output of the
 * connector's `build_report` skill) into a real .pptx Buffer.
 *
 * This wires the connector into PRISM's existing presentation pipeline: it
 * reuses the same `pptxgenjs` dependency and the shared style system in
 * `lib/pptx/styles.ts`, so audit decks match the house look. An ads-audit deck
 * (KPIs + bar charts + recommendations) has a different structure than the
 * 4-pillar marketing templates, so it gets its own focused layout renderer
 * rather than being forced through `generatePresentation`.
 */
import PptxGenJS from 'pptxgenjs';
import { COLOR_PALETTES, FONTS, FONT_SIZES, SLIDE } from '../pptx/styles';

// ── Deck spec types (mirror the connector's build_report output) ──
export interface DeckKpi { label: string; value: string | number }
export interface DeckChart {
  type: 'bar' | 'line';
  labels: string[];
  series: Array<{ name: string; data: number[] }>;
}
export interface DeckSlide {
  layout: 'cover' | 'kpi' | 'bar-chart' | 'bullets' | 'table' | 'closing';
  title?: string;
  subtitle?: string;
  kpis?: DeckKpi[];
  chart?: DeckChart;
  bullets?: string[];
  rows?: Array<Record<string, string | number | null>>;
}
export interface DeckSpec {
  title: string;
  slides: DeckSlide[];
}

const PALETTE = COLOR_PALETTES.executive;
const W = SLIDE.WIDTH;
const MARGIN = 0.6;

/** Render a connector deck spec to a .pptx Buffer. */
export async function renderDeck(deck: DeckSpec): Promise<Buffer> {
  const pptx = new PptxGenJS();
  pptx.defineLayout({ name: 'PRISM', width: SLIDE.WIDTH, height: SLIDE.HEIGHT });
  pptx.layout = 'PRISM';
  pptx.author = 'PRISM Ads Connector';
  pptx.title = deck.title || 'Ads Audit';

  const slides = Array.isArray(deck.slides) ? deck.slides : [];
  if (slides.length === 0) addCover(pptx, { layout: 'cover', title: deck.title || 'Ads Audit' });

  for (const slide of slides) {
    switch (slide.layout) {
      case 'cover': addCover(pptx, slide); break;
      case 'kpi': addKpi(pptx, slide); break;
      case 'bar-chart': addChart(pptx, slide); break;
      case 'table': addTable(pptx, slide); break;
      case 'closing':
      case 'bullets': addBullets(pptx, slide); break;
      default: addBullets(pptx, slide);
    }
  }

  // pptxgenjs returns a Node Buffer when outputType is 'nodebuffer'.
  const out = await pptx.write({ outputType: 'nodebuffer' });
  return out as Buffer;
}

function newSlide(pptx: any) {
  const slide = pptx.addSlide();
  slide.background = { color: PALETTE.background };
  return slide;
}

function addTitle(slide: any, text: string) {
  slide.addText(text || '', {
    x: MARGIN, y: 0.4, w: W - MARGIN * 2, h: 0.8,
    fontSize: FONT_SIZES.HEADING, bold: true, color: PALETTE.text, fontFace: FONTS.TITLE,
  });
  slide.addShape('line', { x: MARGIN, y: 1.25, w: W - MARGIN * 2, h: 0, line: { color: PALETTE.secondary, width: 2 } });
}

function addCover(pptx: any, s: DeckSlide) {
  const slide = newSlide(pptx);
  slide.background = { color: PALETTE.primary };
  slide.addText(s.title || 'Ads Audit', {
    x: MARGIN, y: 2.5, w: W - MARGIN * 2, h: 1.6,
    fontSize: FONT_SIZES.TITLE_SLIDE, bold: true, color: 'FFFFFF', fontFace: FONTS.TITLE,
  });
  if (s.subtitle) {
    slide.addText(s.subtitle, {
      x: MARGIN, y: 4.2, w: W - MARGIN * 2, h: 0.8,
      fontSize: FONT_SIZES.SUBHEADING, color: 'D1D5DB', fontFace: FONTS.BODY,
    });
  }
  slide.addText('Generated by PRISM Ads Connector', {
    x: MARGIN, y: SLIDE.HEIGHT - 0.7, w: W - MARGIN * 2, h: 0.4,
    fontSize: FONT_SIZES.CAPTION, color: '9CA3AF', fontFace: FONTS.BODY,
  });
}

function addKpi(pptx: any, s: DeckSlide) {
  const slide = newSlide(pptx);
  addTitle(slide, s.title || 'At a glance');
  const kpis = s.kpis || [];
  const cols = Math.min(4, Math.max(1, kpis.length));
  const cardW = (W - MARGIN * 2 - (cols - 1) * 0.3) / cols;
  kpis.slice(0, cols).forEach((k, i) => {
    const x = MARGIN + i * (cardW + 0.3);
    slide.addShape('rect', { x, y: 2.2, w: cardW, h: 2.0, fill: { color: PALETTE.accent }, line: { color: PALETTE.secondary, width: 1 } });
    slide.addText(String(k.value), { x, y: 2.6, w: cardW, h: 0.9, align: 'center', fontSize: 30, bold: true, color: PALETTE.primary, fontFace: FONTS.TITLE });
    slide.addText(k.label, { x, y: 3.5, w: cardW, h: 0.5, align: 'center', fontSize: FONT_SIZES.BODY, color: PALETTE.lightText, fontFace: FONTS.BODY });
  });
}

function addChart(pptx: any, s: DeckSlide) {
  const slide = newSlide(pptx);
  addTitle(slide, s.title || 'Chart');
  const chart = s.chart;
  if (chart && chart.labels?.length && chart.series?.length) {
    const data = chart.series.map((ser) => ({ name: ser.name, labels: chart.labels, values: ser.data }));
    const type = chart.type === 'line' ? pptx.ChartType.line : pptx.ChartType.bar;
    slide.addChart(type, data, {
      x: MARGIN, y: 1.6, w: W - MARGIN * 2, h: s.bullets?.length ? 3.0 : 5.0,
      chartColors: [PALETTE.secondary, PALETTE.primary, '93C5FD'],
      showLegend: chart.series.length > 1, legendPos: 'b',
      showValue: true, dataLabelColor: '374151', dataLabelFontSize: 9,
      catAxisLabelColor: '6B7280', valAxisLabelColor: '6B7280',
      barDir: 'col',
    });
  }
  if (s.bullets?.length) {
    slide.addText(s.bullets.map((b) => ({ text: b, options: { bullet: true, fontSize: FONT_SIZES.CAPTION, color: '374151', fontFace: FONTS.BODY } })), {
      x: MARGIN, y: 4.8, w: W - MARGIN * 2, h: 2.2,
    });
  }
}

function addBullets(pptx: any, s: DeckSlide) {
  const slide = newSlide(pptx);
  addTitle(slide, s.title || 'Recommendations');
  const bullets = s.bullets || [];
  slide.addText(
    bullets.map((b) => ({ text: b, options: { bullet: { indent: 18 }, fontSize: FONT_SIZES.SUBHEADING - 4, color: PALETTE.text, fontFace: FONTS.BODY, paraSpaceAfter: 10 } })),
    { x: MARGIN, y: 1.6, w: W - MARGIN * 2, h: 5.2, valign: 'top' },
  );
}

function addTable(pptx: any, s: DeckSlide) {
  const slide = newSlide(pptx);
  addTitle(slide, s.title || 'Detail');
  const rows = s.rows || [];
  if (!rows.length) return;
  const headers = Object.keys(rows[0]);
  const head = headers.map((h) => ({ text: h.toUpperCase(), options: { bold: true, color: 'FFFFFF', fill: { color: PALETTE.primary }, fontSize: FONT_SIZES.CAPTION, fontFace: FONTS.BODY } }));
  const body = rows.map((r) => headers.map((h) => ({ text: r[h] == null ? '—' : String(r[h]), options: { fontSize: FONT_SIZES.CAPTION, color: '374151', fontFace: FONTS.BODY } })));
  slide.addTable([head, ...body], {
    x: MARGIN, y: 1.6, w: W - MARGIN * 2,
    border: { type: 'solid', color: 'E5E7EB', pt: 1 },
    align: 'left', valign: 'middle', rowH: 0.4,
  });
}
