/**
 * /share/[token] — public, no-login viewer of a brief's insight report.
 *
 * Intentionally minimal: the strategist creates the link, sends it to the
 * client, the client opens it on phone/laptop and sees the headline,
 * audience snapshot, and the verified insight cards. No login wall, no
 * navbar, no editor controls. Watermarked footer signals provenance.
 *
 * This is a Server Component — it fetches the data on the server so the
 * HTML is fully populated before hydration (good for sharing, good for OG
 * unfurls if a client re-shares the link in WhatsApp/Slack).
 */

import { notFound } from 'next/navigation';
import { headers } from 'next/headers';
import styles from './share.module.css';

async function fetchShared(token) {
  const h = await headers();
  const proto = h.get('x-forwarded-proto') || 'https';
  const host  = h.get('host') || 'prism-fluo.vercel.app';
  const res = await fetch(`${proto}://${host}/api/share/${token}`, { cache: 'no-store' });
  if (!res.ok) return null;
  return res.json();
}

export async function generateMetadata({ params }) {
  const { token } = await params;
  const data = await fetchShared(token);
  const brand = data?.brief?.brand || 'Strategic Brief';
  const obj   = data?.brief?.objective || 'Insight Report';
  return {
    title: `${brand} — ${obj}`,
    description: 'Insight report generated by PRISM Council — verified by 7 AI agents before sharing.',
    robots: { index: false, follow: false },  // share links should not be indexed
    openGraph: {
      title: `${brand} — ${obj}`,
      description: 'Verified insight report from PRISM Council.',
    },
  };
}

export default async function SharedReportPage({ params }) {
  const { token } = await params;
  const data = await fetchShared(token);
  if (!data || !data.brief) notFound();

  const { brief, analysis } = data;
  const results  = analysis?.results_json ?? {};
  const headline = results?.overview?.headline   || `${brief.brand} — Strategic Insight`;
  const audSnap  = results?.overview?.audienceSnapshot;
  const charts   = Array.isArray(results?.charts) ? results.charts : [];

  return (
    <div className={styles.page}>
      <header className={styles.topBar}>
        <div className={styles.brand}>
          <div className={styles.brandIcon}>P</div>
          <span className={styles.brandText}>PRISM <em>Council</em></span>
        </div>
        <div className={styles.badge}>Verified Insight Report</div>
      </header>

      <main className={styles.main}>
        <div className={styles.meta}>
          <span className={styles.briefBrand}>{brief.brand}</span>
          {brief.category && <span className={styles.dot}>·</span>}
          {brief.category && <span>{brief.category}</span>}
          {brief.objective && <span className={styles.dot}>·</span>}
          {brief.objective && <span>{brief.objective}</span>}
        </div>

        <h1 className={styles.headline}>{headline}</h1>

        {audSnap && (
          <section className={styles.snapshot}>
            <div className={styles.snapshotLabel}>AUDIENCE SNAPSHOT</div>
            <p>{audSnap}</p>
          </section>
        )}

        <section className={styles.cards}>
          {charts.length === 0 && (
            <div className={styles.emptyState}>
              No published insights yet.
            </div>
          )}
          {charts.map((card, i) => (
            <article key={i} className={styles.card}>
              {card.title && <h2 className={styles.cardTitle}>{card.title}</h2>}
              {card.obs && <p className={styles.cardObs}>{card.obs}</p>}
              {card.stat && (
                <div className={styles.cardStat}>
                  <span className={styles.statLabel}>KEY STAT</span>
                  <span className={styles.statValue}>{card.stat}</span>
                </div>
              )}
              {card.rec && (
                <div className={styles.cardRec}>
                  <span className={styles.recLabel}>RECOMMENDATION</span>
                  <p>{card.rec}</p>
                </div>
              )}
            </article>
          ))}
        </section>
      </main>

      <footer className={styles.footer}>
        <div>
          Generated and verified by <strong>PRISM Council</strong> — every claim
          cross-checked by 7 AI agents before this report was shared.
        </div>
        <a href="/" className={styles.ctaLink}>Learn more →</a>
      </footer>
    </div>
  );
}
